meta_title: "Expedution, organisez votre learning expedition simplement."
meta_description: "Gagnez du temps pour l'organisation de vos séminaires d'exploration."
meta_image: "banner.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@expedution" # indispensable pour les Twitter Cards
